version: '3.8'

networks:
    localdev:
        name: localdev

services:
    main-api:
        build: TwelveFactor/
        restart: always
        ports:
            - "7000:80"
        networks:
            - localdev
