FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base

ARG BUILDCONFIG=RELEASE
ARG VERSION=1.0.0

COPY TwelveFactor.csproj /build/

RUN dotnet restore ./build/TwelveFactor.csproj
    
COPY . ./build/
WORKDIR /build/
RUN dotnet publish ./TwelveFactor.csproj -c $BUILDCONFIG -o out /p:Version=$VERSION

FROM mcr.microsoft.com/dotnet/aspnet:3.1
WORKDIR /app

COPY --from=build /build/out .

ENTRYPOINT ["dotnet", "TwelveFactor.dll"]